# Generated by Django 5.1.2 on 2024-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_vehicle',
            field=models.CharField(blank=True, choices=[('small_van', 'Small Van'), ('box_truck', 'Box Truck'), ('refrigerated_truck', 'Refrigerated Truck'), ('motor_cycle', 'Motor Cycle'), ('cargo_van', 'Cargo Van'), ('dump_truck', 'Dump Truck')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
