# Generated by Django 5.1.2 on 2024-11-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_assigned_vehicle_order_driver_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
