# Generated by Django 5.1.2 on 2025-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.CharField(default=1741109934.143005, max_length=25),
        ),
    ]
